-- local prettier = require("prettier")
--
-- prettier.setup({
--   bin = 'prettier', -- or `'prettierd'` (v0.23.3+)
--   filetypes = {
--     "css",
--     "html",
--     "javascript",
--     "javascriptreact",
--     "json",
--     "less",
--     "markdown",
--     "scss",
--     "typescript",
--     "typescriptreact",
--     "yaml",
--   },
--   cli_options = {
--     tabWidth = true,
--     useTabs = true,
--     print_width = 80,
--     single_quote = true,
--     semi = false,
--     svelteStrictMode = true,
--     jsxSingleQuote = true,
--   }
-- })
