require('core/options')
require('core/keymaps')

require('plugins')
require('plugins/coc')
require('plugins/bufferline')
require('plugins/lualine')
require('plugins/nvim-tree')
require('plugins/floaterm')
require('plugins/fzf')
require('plugins/ccc')
