require('core/options')
require('core/keymaps')

require('plugins')
require('plugins/colorscheme')
require('plugins/transparent')
require('plugins/zero')
require('plugins/telescope')
require('plugins/bufferline')
require('plugins/lualine')
require('plugins/nvim-tree')
require('plugins/indent-lines')
require('plugins/floaterm')
require('plugins/ccc')
